### PR TITLE
Ruleset test

### PR DESCRIPTION
**Pull request by apawsey**
Ok I know this is probably totally in poor taste, or against some ethics of git which I'm not really aware of... so my apologies, this was just one of those things where I wanted to have a play, and it all just got away from me.  At this point it's just to initiate discussion, feedback etc.

So the run down...

- Refactored ValidationConfig into ValidationRuleset, standalone ruleset that can be used to validate any object against it's rules.
- Added ValidatorLite, instance specific validator, but never observes properties (so can't be used for live validation), or attempts to work with decorators.
- Refactored Validator to instance specific validator.  Works on same principles as decorators, and automatically merges any decorator rules with it's own ruleset.
- Refactored binding behaviour into live binding, and plain rendering validation.  Live binding will show errors only once user has touched field (based on focus event), or when pushed by manual validate call.  Plain binding, will only show rules when pushed via manual validate call.
- Added custom validation rule allowing the use of custom rules registered with Validate.js.

Like I said, this is just a big experiment for me.  Pushing this as a PR is also not a good idea, but I didn't really know how to point anyone to my fork.

Oh and as @EisenbergEffect said he doesn't like inheritance, I doubt this will do anything to change hid mind :tired_face:

### CODE REVIEW

**Comment by apawsey** [comment]
Oh the samples have been updated with the new features as well.  I removed the dist because it was a mess, sorry.  But build with gulp watch and it should be all fine.

**Comment by mbroadst** [comment]
I think you'll do much better getting your point across if you remove the needlessly removed files. It's incredibly difficult to focus on what you're actually changing when I have to scroll through 70+ files that are just deletions 😄

**Comment by apawsey** [comment]
I agree entirely!!!, but you still end up with an huge file count because all of the dist files change as well.  Best way to demonstrate this would be an actual demo, but not spending enough time doing this normally, I'm not sure if there's an easy way to put that together!  I'm just not used to git and PR's etc, so I generally make a mess of them.  Sorry any/everyone

**Comment by mbroadst** [comment]
@apawsey you can omit updating the dist files. You'd only need to do that if you wanted to "ship" the feature. Since you're just trying to show off the changes, simply don't include anything in `dist` as part of your commit.

**Comment by apawsey** [comment]
ok, good point.  Next question is, do I just create a new commit, without the dists (and I assume a new PR), or is there a way to revise the commits I already have? (told you I'm not super big on working with git)

**Comment by apawsey** [comment]
see #58

**Pull request closed without merging**
