### PR TITLE
fix(numericality): missing configuration argument

### PR DESCRIPTION
**Pull request by searus**
the numericality validation is not working for the fluent api as the configuration is not passed through the call stack.

### CODE REVIEW

**Comment by PWKad** [comment]
@EisenbergEffect CLA confirmation request (I think I remember searus contributing elsewhere but couldn't find anything yet to confirm)

**Comment by PWKad** [comment]
@searus If you don't mind could you add the config for https://github.com/aurelia/validatejs/blob/master/src/validator.js#L35-L58 and https://github.com/aurelia/validatejs/blob/master/src/validator.js#L75-L78 also?  If not no biggie I can add they just all need the same thing.

**Comment by EisenbergEffect** [comment]
CLA Confirmed.

**Comment by searus** [comment]
Travelling at the moment but will do it later today

**Comment by searus** [comment]
Added them in now

**Pull request merged**
