### PR TITLE
chore(deps): clean up package.json

### PR DESCRIPTION
**Pull request by PWKad**
@EisenbergEffect Does this look right?  I kept getting warnings after the last round of cleanups.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Basically, you need:

jspm.peerDependencies for jspm 0.17
jspm.dependencies for < jspm 0.17
dependencies for npm (Webkit and probably our future stuff)
and don't forget bower

The package.json above looks correct but make sure the deps are mirrored in bower.json as well.

**Comment by PWKad** [comment]
Double-check now - if that looks good I'll make a mental breakpoint here for future reference to look back here when I screw something up.

**Comment by mbroadst** [comment]
@PWKad you're missing `jspm.dependencies` for:
```
      "aurelia-polyfills": "^1.0.0-beta.1.1.3",
      "validate.js": "^0.9.0"
```

have I mentioned yet I despise jspm 😄

**Comment by EisenbergEffect** [comment]
@PWKad For tomorrow's release, we'll want to have this merged and also include the missing dependencies per @mbroadst

**Pull request closed without merging**
