### PR TITLE
Type hints and documentation for #10

### PR DESCRIPTION
**Pull request by derkork**
I have added type hints and documentation in order to fix issue #10. Please let me know if this is ok this way or if some changes are required. Thanks.

### CODE REVIEW

**Comment by PWKad** [comment]
Awesome I'll take a look at this and get it merged in ASAP - have you signed the CLA yet?

**Comment by derkork** [comment]
Yes I have signed the CLA before sending the pull request. Thanks for
having a look at it.

2016-05-25 23:27 GMT+02:00 Patrick Walters <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
@derkork There appear to be changes. Would you be willing to rebase on master? @jdanyow has some work that's going to be committed soon. It might be best to wait until he has that in. @jdanyow Can you ping @derkork here when he can rebase to add the types and api comments?

**Comment by derkork** [comment]
I see. Well just ping me when you're ready I'll rebase the branch then.

**Comment by EisenbergEffect** [comment]
@derkork Can you take a look now?

**Comment by derkork** [comment]
I'm on vacation currently, but I'll try to squeeze it in next week.

2016-06-29 16:32 GMT+02:00 Rob Eisenberg <notifications@github.com>:

**Comment by EisenbergEffect** [comment]
@derkork Hope you had a nice vacation. Just wanted to check in and see if you would have time this week to update this PR. Thanks!

**Comment by EisenbergEffect** [comment]
Ok, closing this PR for now. If you have time, please re-submit based on master. Thank you!

**Pull request closed without merging**
